spring:
  application:
    name: ticketsV2

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200
    refreshTokenExpiration: 604800
    redirectTokenExpirtation: 900
  profiles:
    active: dev

